#!/bin/bash
set -ueo pipefail

basedir=/var/lib/qubes/vm-kernels/
kvers=()
all=0
while read -r line; do
  if [[ $line == usr/lib/dracut/* ]]; then
    all=1
    continue
  fi
  if [[ ! -f "/${line}/vmlinuz" ]]; then
    continue
  fi
  kver=$(basename $line)
  kvers+=($kver)
done

if (( all )); then
  # Regenerate all installed kernels.
  kvers=()
  for f in /usr/lib/modules/*/vmlinuz; do
    kvers+=($(basename $(dirname $f)))
  done
fi

for kver in "${kvers[@]}"; do
  qubes-prepare-vm-kernel "${kver}"
done
